### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by collin999** [Sg4Dylan/vapoursynth-fsrcnn-ncnn-vulkan#2]
水平有限，fsrcnn编译失败，能不能发个vs版的dll呀，我只能用Waifu2x-w2xc，不知哪个模式是基于fsrcnn的。
已经发了个邮件给楼主，万分感谢！

**Comment by Sg4Dylan** [comment]
模型名称包含 `upconv_7` 或者 输出是反卷积层的 7 层 waifu2x 实现使用的是 FSRCNN。
VapourSynth 移植版本建议使用 [VapourSynth-Waifu2x-caffe](https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe) 或者 [VapourSynth-Waifu2x-caffe](https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe) 。
